SnakeTn\Reward\Entity\RewardPointMovement:
  type: entity
  repositoryClass: SnakeTn\Reward\Repository\RewardPointMovementRepository
  table: reward_point_movement
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    value:
      type: integer
    origin:
      type: string
    createdAt:
      type: datetime
      column: created_at
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      column: updated_at
      gedmo:
        timestampable:
          on: update
  manyToOne:
    customer:
      targetEntity: Sylius\Component\Core\Model\Customer
      joinColumn:
        name: customer_id
        referencedColumnName: id
